### PR TITLE
Add image caching functionality

### PR DESCRIPTION
**Pull request by AndreiEvstratenko**
# Pull Request

## Description

- Images cache by url
- Remove freeze when image downloads

### Types of changes

- [ ] Bug fix
- [ ] New feature
- [x] Maintenance

### CODE REVIEW

**Comment by brentchow** [comment]
How long does the image last in the cache? Is there a way to break the cache?

**Comment by AndreiEvstratenko** [comment]
> How long does the image last in the cache? Is there a way to break the cache?

There is no way to break the cache now, if we need I can add this. Images are stored in cache while the application is running

@brentchow

**Comment by brentchow** [comment]
If a user [force closes](https://support.apple.com/en-us/HT201330) the app, does it clear the cache?

**Comment by AndreiEvstratenko** [comment]
> If a user [force closes](https://support.apple.com/en-us/HT201330) the app, does it clear the cache?

Yes. Cache will be cleared.

**Comment by brentchow** [comment]
I don’t think this is needed for a demo.

Making the demo too complicated doesn’t help developers. It's already too complicated IMHO.

**Pull request closed without merging**
